trigger:
- main

stages:
- stage: DeployDev
  jobs:
  - job: Deploy
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'MyServiceConnection'
        KeyVaultName: 'aks-demo-kv1'
        SecretsFilter: '*'
        RunAsPreJob: true

    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'MyServiceConnection'
        azureResourceGroup: 'aks-demo-rg'
        kubernetesCluster: 'aks-demo-cluster'
        namespace: 'dev'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'manifests/deployment.yaml'

- stage: DeployQA
  dependsOn: DeployDev
  jobs:
  - job: Deploy
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'MyServiceConnection'
        azureResourceGroup: 'aks-demo-rg'
        kubernetesCluster: 'aks-demo-cluster'
        namespace: 'qa'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'manifests/deployment.yaml'

- stage: DeployProd
  dependsOn: DeployQA
  jobs:
  - job: Deploy
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'MyServiceConnection'
        azureResourceGroup: 'aks-demo-rg'
        kubernetesCluster: 'aks-demo-cluster'
        namespace: 'prod'
        command: 'apply'
        useConfigurationFile: true
        configuration: 'manifests/deployment.yaml'